# Generated by Django 3.1.2 on 2020-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('emergency', models.IntegerField(default=3)),
                ('oper', models.IntegerField(default=1)),
                ('room', models.IntegerField(default=1)),
            ],
        ),
    ]
