# Generated by Django 3.1.2 on 2020-10-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm', models.TextField(blank=True)),
                ('choo', models.TextField(blank=True)),
                ('back', models.TextField(blank=True)),
                ('nmc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.IntegerField(default=1)),
                ('oper', models.IntegerField(default=0)),
            ],
        ),
    ]
