# Generated by Django 3.1.2 on 2020-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bed',
        ),
        migrations.AddField(
            model_name='patient',
            name='ETA_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETA_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETA_S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETA_U',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETE_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETE_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETE_S',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='ETE_U',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hos',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
