# Generated by Django 3.1.2 on 2020-10-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0002_auto_20201020_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_B',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_C',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_S',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_U',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_B',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_C',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_S',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_U',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
