# Generated by Django 3.1.2 on 2020-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0003_auto_20201025_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ETA_B',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_C',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_S',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_U',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_B',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_C',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_S',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_U',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
