# Generated by Django 3.1.2 on 2020-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0004_auto_20201025_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ETA_B',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_C',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_S',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETA_U',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_B',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_C',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_S',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ETE_U',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hos',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
