# Generated by Django 3.1.2 on 2020-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0005_auto_20201025_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hos',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
