# Generated by Django 3.1.2 on 2020-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0006_auto_20201025_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hos',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
