# Generated by Django 3.1.2 on 2020-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0007_auto_20201025_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='by',
        ),
        migrations.AlterField(
            model_name='patient',
            name='hos',
            field=models.IntegerField(default=0),
        ),
    ]
