# Generated by Django 3.1.2 on 2020-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0010_patient_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.CharField(default='0', max_length=45),
        ),
    ]
