# Generated by Django 3.1.2 on 2020-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0011_auto_20201026_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='by',
            field=models.IntegerField(default=0),
        ),
    ]
