# Generated by Django 3.1.2 on 2020-10-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0012_patient_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='end',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='start',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
