# Generated by Django 3.1.2 on 2020-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerapp', '0013_auto_20201027_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='end',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='start',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
